id: P60600AA8
initial_creation_type: ocr
source_metadata:
  volumes:
    373ffe8619db437badb742a28d883a73:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
